# Generated by Django 5.0 on 2023-12-16 20:17

import fastapi_django.db.base
from django.db import migrations, models

import fastapi_django.db.primary_key


class Migration(migrations.Migration):
    replaces = [
        ("fastapi_django", "0001_initial"),
        ("fastapi_django", "0002_user_deleted_at_alter_user_id_and_more"),
        ("fastapi_django", "0003_alter_user_id"),
        ("fastapi_django", "0004_alter_user_id"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=fastapi_django.db.pk.uuid_generate_v1mc,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "firebase_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["id", "deleted_at"], name="user_id_deleted_at_idx"
                    )
                ],
            },
        ),
    ]
