# Generated by Django 5.0 on 2023-12-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Value("uuid_generate_v1mc()"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "firebase_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
