# Generated by Django 5.0 on 2023-12-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fastapi_django", "0002_user_deleted_at_alter_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                db_default=models.Value("uuid_generate_v1mc()"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
