# Generated by Django 5.0 on 2023-12-16 20:16

import fastapi_django.db.base
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fastapi_django", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=fastapi_django.db.base.uuid_generate_v1mc,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
